name: 'Zip action'
description: 'Github action used to zip a folder for lambda use'
author: 'Fixter'
inputs: 
  target:
    description: 'Folders/files to zip'
    default: './*'
  workdir:
    description: 'Folder to cd into before running zip'
    default: './tmp'
  destination:
    description: 'Path of the output zip'
    default: '../service.zip'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TARGET: ${{ inputs.target }}
    WORKDIR: ${{ inputs.workdir }}
    DESTINATION: ${{ inputs.destination }}
